#version: "3"
services: 
  app:
    build: ./app/
    image: event-planner-api:latest 
    container_name: event-planner-api
    restart: unless-stopped
    env_file:
      - .env # - ./app/.env
    volumes:
      - ./app:/app
      - ./images:/data/images
    depends_on:
      - db
    networks:
      - event-planner-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  web:
    image: nginx:latest
    container_name: event-planner-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - event-planner-network
  db:
    image: postgres:16-alpine
    container_name: event-planner-db
    restart: unless-stopped
    env_file:
    - ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - event-planner-network
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq_for_planner
    hostname: rabbitmq
    restart: unless-stopped
    env_file:
    - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP protocol
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - event-planner-network
  ml_worker:
    build: ./app/
    environment:
      - PYTHONPATH=/:/app/
    command: python /ml_worker/main.py 
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./ml_worker:/ml_worker 
      - ./images:/data/images 
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      - event-planner-network
    deploy:
      replicas: 2

volumes:
  postgres_data:
  rabbitmq_data:
  ml_worker_data:

networks:
  event-planner-network:
    name: event-planner-network
    driver: bridge
